# 📘 CH07. 데이터 탐색(EDA) — 강의용 노트북

정규 4시간 수업 진행용입니다. Notion(md) 문서와 동일한 깊이로 구성했습니다 (🌙 더 깊이 알아보기 자율학습 섹션만 제외).

01. EDA 기초 · 02. 데이터 선택 · 03. 그룹 분석

---

# 📘 CH07-01. EDA 기초 (데이터 파악 및 요약)

## 🤔 먼저 생각해보기

> **처음 보는 인사팀 엑셀 파일을 받았을 때, 몇백 줄을 다 눈으로 읽어봐야 할까요?**

새로운 데이터를 받으면 가장 먼저 해야 할 일은 "이 데이터가 대략 어떻게 생겼는지" 빠르게 훑어보는 것입니다. 행이 몇 개인지, 어떤 컬럼이 있는지, 빠진 값은 없는지 등을 빠르게 확인하는 과정을 **EDA(Exploratory Data Analysis, 탐색적 데이터 분석)**라고 합니다.

---

## 📖 핵심 개념

앞으로 이 챕터 전체에서 아래 직원 데이터를 예시로 사용합니다.

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import pandas as pd
import numpy as np

data = {
    "이름": ["김민준", "이서연", "박도윤", "최지우", "정하윤",
             "강서준", "조예은", "윤지호", "임수아", "한도현"],
    "나이": [29, 34, 41, 26, 38, 45, 31, np.nan, 27, 33],
    "부서": ["개발팀", "마케팅팀", "개발팀", "인사팀", "마케팅팀",
             "개발팀", "인사팀", "마케팅팀", "개발팀", "인사팀"],
    "직무": ["Developer", "Marketer", "Developer", "HR", "Marketer",
             "Developer", "HR", "Marketer", "Developer", "HR"],
    "급여": [4200, 3800, 5600, 3600, 4100, 6200, 3900, 4300, 4000, 3700],
    "도시": ["서울", "부산", "서울", "대구", "서울", "인천", "부산", "서울", "대구", "서울"]
}

df = pd.DataFrame(data)
print(df)
```

</details>

In [2]:
# 코드 입력

import pandas as pd
import numpy as np

data = {
    "이름": ["김민준", "이서연", "박도윤", "최지우", "정하윤",
             "강서준", "조예은", "윤지호", "임수아", "한도현"],
    "나이": [29, 34, 41, 26, 38, 45, 31, np.nan, 27, 33],
    "부서": ["개발팀", "마케팅팀", "개발팀", "인사팀", "마케팅팀",
             "개발팀", "인사팀", "마케팅팀", "개발팀", "인사팀"],
    "직무": ["Developer", "Marketer", "Developer", "HR", "Marketer",
             "Developer", "HR", "Marketer", "Developer", "HR"],
    "급여": [4200, 3800, 5600, 3600, 4100, 6200, 3900, 4300, 4000, 3700],
    "도시": ["서울", "부산", "서울", "대구", "서울", "인천", "부산", "서울", "대구", "서울"]
}

df = pd.DataFrame(data)

df

    이름    나이    부서         직무    급여  도시
0  김민준  29.0   개발팀  Developer  4200  서울
1  이서연  34.0  마케팅팀   Marketer  3800  부산
2  박도윤  41.0   개발팀  Developer  5600  서울
3  최지우  26.0   인사팀         HR  3600  대구
4  정하윤  38.0  마케팅팀   Marketer  4100  서울
5  강서준  45.0   개발팀  Developer  6200  인천
6  조예은  31.0   인사팀         HR  3900  부산
7  윤지호   NaN  마케팅팀   Marketer  4300  서울
8  임수아  27.0   개발팀  Developer  4000  대구
9  한도현  33.0   인사팀         HR  3700  서울

### 1) 데이터 미리보기 — `head()`, `tail()`, `sample()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.head())        # 앞에서 5개 행 (기본값)
print(df.head(3))        # 앞에서 3개 행만
print(df.tail(3))         # 뒤에서 3개 행
print(df.sample(3))       # 무작위로 3개 행 (실행할 때마다 결과가 달라짐)
print(df.sample(3, random_state=42))   # random_state 고정 시 항상 같은 결과
```

</details>

In [55]:
# 코드 입력
df.head() # 앞에서 5개 호출

print(df.head(3)) # 호출 행 개수 지정 가능
print("=" * 50)
print(df.tail(3))
print("=" * 50)
print(df.sample(3))
print("=" * 50)
print(df.sample(3, random_state = 42))
print("=" * 50)

    이름    나이    부서         직무    급여  도시
0  김민준  29.0   개발팀  Developer  4200  서울
1  이서연  34.0  마케팅팀   Marketer  3800  부산
2  박도윤  41.0   개발팀  Developer  5600  서울
==================================================
    이름    나이    부서         직무    급여  도시
7  윤지호   NaN  마케팅팀   Marketer  4300  서울
8  임수아  27.0   개발팀  Developer  4000  대구
9  한도현  33.0   인사팀         HR  3700  서울
==================================================
    이름    나이    부서         직무    급여  도시
4  정하윤  38.0  마케팅팀   Marketer  4100  서울
5  강서준  45.0   개발팀  Developer  6200  인천
6  조예은  31.0   인사팀         HR  3900  부산
==================================================
    이름    나이    부서         직무    급여  도시
8  임수아  27.0   개발팀  Developer  4000  대구
1  이서연  34.0  마케팅팀   Marketer  3800  부산
5  강서준  45.0   개발팀  Developer  6200  인천
==================================================

> 💡 `head()`/`tail()`은 "순서대로" 일부를 보여주고, `sample()`은 "무작위로" 골라서 보여줍니다. 데이터가 특정 순서로 정렬되어 있을 때는 `sample()`로 훑어보는 것이 데이터 전체의 특징을 더 골고루 파악하는 데 유리합니다.

### 2) 구조 및 요약 정보 — `info()`, `shape`, `dtypes`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.shape)     # (10, 6)  — (행 개수, 열 개수)
print(df.dtypes)     # 각 컬럼의 자료형
```

</details>

In [57]:
# 코드 입력
print(df.shape)
print(df.dtypes)

(10, 6)
이름     object
나이    float64
부서     object
직무     object
급여      int64
도시     object
dtype: object

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df.info()
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 10 entries, 0 to 9
# Data columns (total 6 columns):
#  #   Column  Non-Null Count  Dtype
# ---  ------  --------------  -----
#  0   이름      10 non-null     object
#  1   나이      9 non-null      float64   ← 나이에 결측치 1개가 있음을 바로 알 수 있음
#  2   부서      10 non-null     object
#  3   직무      10 non-null     object
#  4   급여      10 non-null     int64
#  5   도시      10 non-null     object
# dtypes: float64(1), int64(1), object(4)
```

</details>

In [58]:
# 코드 입력
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      10 non-null     object
 1   나이      9 non-null      float64
 2   부서      10 non-null     object
 3   직무      10 non-null     object
 4   급여      10 non-null     int64
 5   도시      10 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 612.0+ bytes

> 💡 `info()`는 전체 행 개수, 각 컬럼의 결측치 없는 개수(Non-Null Count), 자료형을 한눈에 보여줘서 **데이터 품질을 가장 빠르게 점검**할 수 있는 함수입니다.

### 3) 기술 통계량 — `describe()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.describe())          # 기본값: 수치형 컬럼(나이, 급여)만 통계 요약
#              나이           급여
# count   9.000000    10.000000
# mean   33.777778   4340.000000
# std     6.320783    782.887334
# min    26.000000   3600.000000
# 25%    29.000000   3825.000000
# 50%    32.000000   4050.000000
# 75%    37.750000   4275.000000
# max    45.000000   6200.000000
```

</details>

In [59]:
# 기본값: 수치형 컬럼(나이, 급여)만 통계 요약
df.describe()

              나이           급여
count   9.000000    10.000000
mean   33.777778  4340.000000
std     6.457124   861.781101
min    26.000000  3600.000000
25%    29.000000  3825.000000
50%    33.000000  4050.000000
75%    38.000000  4275.000000
max    45.000000  6200.000000

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.describe(include="all"))   # 모든 컬럼(문자열 포함) 통계 요약
#         이름   나이     부서      직무    급여   도시
# count   10   9.000000   10      10   10.000000  10
# unique  10   NaN         3       3   NaN         4
# top    김민준  NaN       개발팀  Developer  NaN     서울
# freq    1    NaN         4       4   NaN         5
# mean   NaN  33.777778  NaN     NaN  4340.000000  NaN
# ...
```

</details>

In [61]:
# 모든 컬럼(문자열 포함) 통계 요약


df.describe(include="all")

         이름         나이   부서         직무           급여   도시
count    10   9.000000   10         10    10.000000   10
unique   10        NaN    3          3          NaN    4
top     김민준        NaN  개발팀  Developer          NaN   서울
freq      1        NaN    4          4          NaN    5
mean    NaN  33.777778  NaN        NaN  4340.000000  NaN
std     NaN   6.457124  NaN        NaN   861.781101  NaN
min     NaN  26.000000  NaN        NaN  3600.000000  NaN
25%     NaN  29.000000  NaN        NaN  3825.000000  NaN
50%     NaN  33.000000  NaN        NaN  4050.000000  NaN
75%     NaN  38.000000  NaN        NaN  4275.000000  NaN
max     NaN  45.000000  NaN        NaN  6200.000000  NaN

> ⚠️ **`include='all'` 옵션은 필수로 기억해야 합니다.** 기본 `describe()`는 숫자형 컬럼만 보여주기 때문에, 문자열 컬럼(부서, 직무 등)의 고유값 개수·최빈값 같은 정보는 `include='all'`을 붙여야 함께 확인할 수 있습니다.

### 4) 결측치 확인 — `isnull()`/`isna()`와 `sum()`의 조합

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.isnull())        # 각 셀이 결측치인지 True/False로 표시
print(df.isna())           # isnull()과 완전히 동일한 함수 (이름만 다름, 별칭 관계)

print(df.isnull().sum())    # 컬럼별 결측치 개수 — 실무에서 가장 많이 쓰는 조합!
# 이름    0
# 나이    1
# 부서    0
# 직무    0
# 급여    0
# 도시    0
```

</details>

In [64]:
# 각 셀이 결측치인지 True/False로 표시
#print(df.isnull())

# isnull()과 완전히 동일한 함수 (이름만 다름, 별칭 관계)
#print(df.isna())

# 컬럼별 결측치 개수 — 실무에서 가장 많이 쓰는 조합!
print(df.isnull().sum())

이름    0
나이    1
부서    0
직무    0
급여    0
도시    0
dtype: int64

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.isnull().sum().sum())   # 전체 결측치 총 개수 (모든 컬럼 합산)
print(df["나이"].isnull().sum())  # 특정 컬럼의 결측치 개수만 확인
```

</details>

In [66]:
# 코드 입력
print(df.isnull().sum().sum())
print(df['나이'].isnull().sum())

1
1

### 5) 고유값 및 빈도수 — `unique()`, `nunique()`, `value_counts()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df["부서"].unique())      # ['개발팀' '마케팅팀' '인사팀']  — 중복 없는 값 목록 (배열로 반환)
print(df["부서"].nunique())      # 3   — 고유값의 "개수"만 반환
print(df["부서"].value_counts())   # 각 값이 몇 번 등장하는지 개수 (많은 순으로 정렬)
# 개발팀     4
# 마케팅팀   3
# 인사팀     3
```

</details>

In [ ]:
# 코드 입력
print(df['부서'].unique())
print(df['부서'].nunique())
print(df['부서'].value_counts())

['개발팀' '마케팅팀' '인사팀']
3
부서
개발팀     4
마케팅팀    3
인사팀     3
Name: count, dtype: int64

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df["부서"].value_counts(normalize=True))   # 개수 대신 비율(%)로 확인
# 개발팀     0.4
# 마케팅팀   0.3
# 인사팀     0.3
```

</details>

In [ ]:
# 코드 입력
print(df['부서'].value_counts(normalize = True)) # 정규화(DB 정규화 아님)

부서
개발팀     0.4
마케팅팀    0.3
인사팀     0.3
Name: proportion, dtype: float64

### 6) 서로 다른 방식 비교 — `unique()` vs `value_counts()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
dept = df["부서"]

print(dept.unique())         # ['개발팀' '마케팅팀' '인사팀']  ← "어떤 값들이 있는지" 목록만
print(dept.nunique())         # 3                              ← "몇 종류인지" 개수만
print(dept.value_counts())    # 개발팀 4 / 마케팅팀 3 / 인사팀 3  ← "각각 몇 번씩" 등장하는지
```

</details>

In [ ]:
# 코드 입력

| 함수 | 반환하는 것 | 반환 타입 |
|---|---|---|
| `unique()` | 중복 제거된 값 목록 | NumPy 배열 |
| `nunique()` | 고유값의 개수(숫자 하나) | 정수 |
| `value_counts()` | 값별 등장 횟수 | Series (값이 인덱스, 개수가 값) |

> 💡 **핵심 요약**: "어떤 값들이 있는지"만 궁금하면 `unique()`, "몇 종류인지 개수"만 필요하면 `nunique()`, "각 값이 얼마나 자주 나오는지"까지 알고 싶으면 `value_counts()`를 사용하세요.

### 7) 데이터 정렬 — `sort_values()`, `sort_index()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.sort_values("급여"))                                   # 급여 오름차순
print(df.sort_values("급여", ascending=False))                   # 급여 내림차순
print(df.sort_values(["부서", "급여"], ascending=[True, False]))  # 부서는 오름차순, 급여는 내림차순
```

</details>

In [73]:
# 코드 입력
#print(df.sort_values("급여"))
#print("=" * 50)
#print(df.sort_values("급여", ascending = False))
#print("=" * 50)
print(df.sort_values(["부서", "급여"], ascending = [True, False]))

    이름    나이    부서         직무    급여  도시
5  강서준  45.0   개발팀  Developer  6200  인천
2  박도윤  41.0   개발팀  Developer  5600  서울
0  김민준  29.0   개발팀  Developer  4200  서울
8  임수아  27.0   개발팀  Developer  4000  대구
7  윤지호   NaN  마케팅팀   Marketer  4300  서울
4  정하윤  38.0  마케팅팀   Marketer  4100  서울
1  이서연  34.0  마케팅팀   Marketer  3800  부산
6  조예은  31.0   인사팀         HR  3900  부산
9  한도현  33.0   인사팀         HR  3700  서울
3  최지우  26.0   인사팀         HR  3600  대구

> 💡 `sort_values()`는 값 기준, `sort_index()`는 인덱스(행 번호/라벨) 기준으로 정렬합니다. 여러 컬럼을 기준으로 정렬할 때는 컬럼명을 리스트로 넘기고, `ascending`도 각 컬럼에 맞춰 리스트로 지정할 수 있습니다.

### 8) 상위/하위 값 빠르게 뽑기 — `nlargest()`, `nsmallest()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.nlargest(3, "급여"))    # 급여 상위 3명
print(df.nsmallest(3, "나이"))   # 나이 하위 3명 (가장 어린 3명)
```

</details>

In [74]:
# 코드 입력
print(df.nlargest(3, "급여"))
print("=" * 50)
print(df.nsmallest(3, "나이"))

    이름    나이    부서         직무    급여  도시
5  강서준  45.0   개발팀  Developer  6200  인천
2  박도윤  41.0   개발팀  Developer  5600  서울
7  윤지호   NaN  마케팅팀   Marketer  4300  서울
==================================================
    이름    나이   부서         직무    급여  도시
3  최지우  26.0  인사팀         HR  3600  대구
8  임수아  27.0  개발팀  Developer  4000  대구
0  김민준  29.0  개발팀  Developer  4200  서울

> 💡 `df.sort_values("급여", ascending=False).head(3)`과 결과는 같지만, `nlargest()`/`nsmallest()`는 코드가 더 짧고 의도가 명확해서 "상위/하위 N개"를 뽑을 때 실무에서 자주 사용합니다.

### 9) 순위 매기기 — `rank()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df["급여순위"] = df["급여"].rank(ascending=False)          # 급여가 높을수록 1등
print(df[["이름", "급여", "급여순위"]].sort_values("급여순위"))

print(df["급여"].rank(ascending=False, method="min"))      # 동점자는 같은 순위(공동 순위) 부여
```

</details>

In [76]:
# 코드 입력
df["급여순위"] = df["급여"].rank(ascending = False)

print(df[["이름", "급여", "급여순위"]].sort_values("급여순위"))

    이름    급여  급여순위
5  강서준  6200   1.0
2  박도윤  5600   2.0
7  윤지호  4300   3.0
0  김민준  4200   4.0
4  정하윤  4100   5.0
8  임수아  4000   6.0
6  조예은  3900   7.0
1  이서연  3800   8.0
9  한도현  3700   9.0
3  최지우  3600  10.0

> 💡 `rank()`는 값을 정렬하지 않고 각 행이 "몇 등인지"를 새 값으로 돌려줍니다. `sort_values()`가 표 전체의 순서를 바꾸는 것과 달리, `rank()`는 원래 순서를 유지한 채 순위 정보만 추가할 수 있어 "순위 컬럼 만들기"에 적합합니다. 동점 처리는 `method` 옵션(`"average"` 기본, `"min"` 공동순위 등)으로 조절합니다.

### 10) 최댓값·최솟값의 "위치" 찾기 — `idxmax()`, `idxmin()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df["급여"].max())        # 최댓값 "값" 자체 → 6200
print(df["급여"].idxmax())     # 최댓값이 있는 "행 인덱스" → 5

best = df.loc[df["급여"].idxmax()]     # 급여가 가장 높은 직원의 전체 정보
print(best)

youngest = df.loc[df["나이"].idxmin()]  # 나이가 가장 어린 직원의 전체 정보
print(youngest)
```

</details>

In [79]:
# 코드 입력
print(df['급여'].max())
print(df['급여'].idxmax())

best = df.loc[df['급여'].idxmax()]
print(best)

youngest = df.loc[df['나이'].idxmin()]
print(youngest)

6200
5
이름            강서준
나이           45.0
부서            개발팀
직무      Developer
급여           6200
도시             인천
급여순위          1.0
Name: 5, dtype: object
이름       최지우
나이      26.0
부서       인사팀
직무        HR
급여      3600
도시        대구
급여순위    10.0
Name: 3, dtype: object

> 💡 `max()`/`min()`은 값 자체를, `idxmax()`/`idxmin()`은 그 값이 있는 **행의 인덱스**를 돌려줍니다. "급여가 가장 높은 사람이 **누구**인지"처럼 값이 아니라 해당 행 전체가 궁금할 때는 `df.loc[df["급여"].idxmax()]` 패턴으로 조합해서 사용합니다 (이번 소단원의 `loc[]` 없이도, 다음 소단원에서 배울 `loc[]`와 연결되는 대표 패턴입니다).

### 11) 자료형별 컬럼 골라 보기 — `select_dtypes()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.select_dtypes(include="number"))    # 수치형 컬럼만
print(df.select_dtypes(include="object"))    # 문자열(범주형) 컬럼만
print(df.select_dtypes(exclude="number"))    # 수치형을 제외한 나머지
```

</details>

In [82]:
# 코드 입력
#print(df.select_dtypes(include = 'number'))
#print(df.select_dtypes(include = 'object'))

print(df.select_dtypes(exclude = 'number'))

    이름    부서         직무  도시
0  김민준   개발팀  Developer  서울
1  이서연  마케팅팀   Marketer  부산
2  박도윤   개발팀  Developer  서울
3  최지우   인사팀         HR  대구
4  정하윤  마케팅팀   Marketer  서울
5  강서준   개발팀  Developer  인천
6  조예은   인사팀         HR  부산
7  윤지호  마케팅팀   Marketer  서울
8  임수아   개발팀  Developer  대구
9  한도현   인사팀         HR  서울

> 💡 컬럼이 수십~수백 개인 실제 데이터에서는 `select_dtypes()`로 자료형별로 먼저 나눠서 살펴보는 것이 `describe(include="all")`보다 앞선 사전 점검 단계로 유용합니다.

---

## ⚠️ 자주 하는 실수

> ⚠️ `describe()`를 기본값으로만 써서 문자열 컬럼의 통계(최빈값 등)를 놓치는 경우가 흔합니다 — `include='all'` 옵션을 기억하세요.

> ⚠️ `isnull()`과 `isna()`가 다른 함수라고 착각하는 경우가 있는데, 둘은 완전히 동일한 함수의 다른 이름(별칭)입니다.

> ⚠️ `df.isnull()`만 보고 각 셀의 True/False를 눈으로 세려고 하는 경우가 있는데, `.sum()`을 붙여 컬럼별 개수로 요약해서 보는 것이 훨씬 효율적입니다.

> ⚠️ `sort_values()` 같은 함수는 기본적으로 원본을 바꾸지 않고 "새 결과"를 반환합니다. 계속 사용하려면 `df = df.sort_values(...)`처럼 재할당하거나 `inplace=True`를 사용해야 합니다.

> ⚠️ `idxmax()`가 돌려주는 것은 "값"이 아니라 "인덱스"입니다. 최댓값 자체가 필요하면 `max()`를 사용해야 합니다.

---

## 🚀 실무에서는?

> 🚀 새로운 데이터를 받으면 실무자는 거의 항상 `df.head()` → `df.info()` → `df.describe(include='all')` → `df.isnull().sum()` 순서로 훑어보며 데이터의 전반적인 상태를 파악합니다. 이후 `sort_values()`/`nlargest()`로 상위·하위 값을 확인하고, `idxmax()`로 "1등이 누구인지"까지 짚어보면 EDA의 "국룰" 루틴이 하나로 완성됩니다.

---

## 🧩 Check Point

**Q1.** 문자열 컬럼의 통계(최빈값 등)까지 확인하려면 `describe()`에 어떤 옵션을 추가해야 하나요? ① `full=True` ② `include='all'` ③ `all=True` ④ 옵션 불필요
<details><summary>정답</summary>② `include='all'`</details>

**Q2.** 컬럼별 결측치 "개수"를 확인하는 가장 표준적인 조합은? ① `.isnull()` ② `.isnull().sum()` ③ `.dropna()` ④ `.fillna()`
<details><summary>정답</summary>② `.isnull().sum()`</details>

**Q3.** 값의 종류와 각 값이 몇 번 나왔는지까지 함께 보고 싶다면? ① `unique()` ② `nunique()` ③ `value_counts()` ④ `describe()`
<details><summary>정답</summary>③ `value_counts()`</details>

**Q4.** 급여 상위 3명을 가장 간결하게 뽑는 방법은? ① `sort_values()` 후 `head(3)` ② `nlargest(3, "급여")` ③ ①, ② 모두 가능 ④ `describe()`
<details><summary>정답</summary>③ ①, ② 모두 가능 — 결과는 같지만 `nlargest()`가 더 간결합니다</details>

**Q5.** "급여가 가장 높은 행의 인덱스"를 돌려주는 함수는? ① `max()` ② `idxmax()` ③ `nlargest()` ④ `rank()`
<details><summary>정답</summary>② `idxmax()` — `max()`는 값 자체를 돌려줍니다</details>

---

## 💻 실습

> 🔧 아래 코드 블록은 ipynb 셀로 그대로 변환됩니다. 난이도가 단계적으로 올라갑니다.

In [ ]:
# TODO 1 (미리보기): df의 앞 3개, 뒤 3개 행을 각각 출력하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.head(3))
print(df.tail(3))
```

</details>

In [166]:
# 코드 입력
print(df.head(3))
print(df.tail(3))

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667  31 ~ 40세    하
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상
8  임수아  27   개발팀  Developer  4000  대구  5000.000000    30세 이하    중
9  한도현  33   인사팀         HR  3700  서울  3733.333333  31 ~ 40세    하

In [ ]:
# TODO 2 (구조 확인): df의 shape와 각 컬럼의 dtype을 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.shape)
print(df.dtypes)
```

</details>

In [167]:
# 코드 입력
print(df.shape)
print(df.dtypes)

(10, 9)
이름          object
나이           int64
부서          object
직무          object
급여           int64
도시          object
부서평균급여     float64
나이대       category
급여등급      category
dtype: object

In [ ]:
# TODO 3 (기술통계): df 전체 컬럼(문자열 포함)의 기술통계를 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.describe(include="all"))
```

</details>

In [168]:
# 코드 입력
print(df.describe(include = 'all'))

         이름         나이   부서         직무           급여   도시       부서평균급여  \
count    10  10.000000   10         10    10.000000   10    10.000000
unique   10        NaN    3          3          NaN    4          NaN
top     김민준        NaN  개발팀  Developer          NaN   서울          NaN
freq      1        NaN    4          4          NaN    5          NaN
mean    NaN  34.000000  NaN        NaN  4340.000000  NaN  4340.000000
std     NaN   6.128259  NaN        NaN   861.781101  NaN   584.110593
min     NaN  26.000000  NaN        NaN  3600.000000  NaN  3733.333333
25%     NaN  29.500000  NaN        NaN  3825.000000  NaN  3816.666667
50%     NaN  33.500000  NaN        NaN  4050.000000  NaN  4066.666667
75%     NaN  37.500000  NaN        NaN  4275.000000  NaN  5000.000000
max     NaN  45.000000  NaN        NaN  6200.000000  NaN  5000.000000

             나이대 급여등급
count         10   10
unique         3    3
top     31 ~ 40세    하
freq           5    4
mean         NaN  NaN
std          NaN  NaN
min          NaN  NaN
25%          NaN  NaN
50%          NaN  NaN
75%          NaN  NaN
max          NaN  NaN

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# TODO 4 (결측치): 컬럼별 결측치 개수와 전체 결측치 총합을 각각 구하세요
```

</details>

In [ ]:
# TODO 4 (결측치): 컬럼별 결측치 개수와 전체 결측치 총합을 각각 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.isnull().sum())
print(df.isnull().sum().sum())
```

</details>

In [170]:
# 코드 입력
print(df.isna().sum())
print(df.isna().sum().sum())

이름        0
나이        0
부서        0
직무        0
급여        0
도시        0
부서평균급여    0
나이대       0
급여등급      0
dtype: int64
0

In [ ]:
# TODO 5 (고유값): "직무" 컬럼의 고유값 목록, 고유값 개수, 값별 빈도수를 각각 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df["직무"].unique())
print(df["직무"].nunique())
print(df["직무"].value_counts())
```

</details>

In [171]:
# 코드 입력
print(df['직무'].unique())
print(df['직무'].nunique())
print(df['직무'].value_counts())

['Developer' 'Marketer' 'HR']
3
직무
Developer    4
Marketer     3
HR           3
Name: count, dtype: int64

In [ ]:
# TODO 6 (정렬): 급여를 기준으로 내림차순 정렬한 뒤,
#         nlargest()로 상위 3명을 뽑은 결과와 값이 같은지 비교하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.sort_values("급여", ascending=False).head(3))
print(df.nlargest(3, "급여"))
```

</details>

In [172]:
# 코드 입력
sorted_df = df.sort_values('급여', ascending = False)
print(sorted_df.head(3))

df.nlargest(3, '급여')

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
5  강서준  45   개발팀  Developer  6200  인천  5000.000000    40세 이상    상
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
5  강서준  45   개발팀  Developer  6200  인천  5000.000000    40세 이상    상
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상

In [ ]:
# TODO 7 (순위): 나이를 기준으로 "나이순위" 컬럼을 만들고 (많을수록 1등),
#         이름, 나이, 나이순위를 순위 순서로 출력하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
df["나이순위"] = df["나이"].rank(ascending=False)
print(df[["이름", "나이", "나이순위"]].sort_values("나이순위"))
```

</details>

In [173]:
# 코드 입력
df['나이순위'] = df['나이'].rank(ascending = False)
print(df[['이름', '나이', '나이순위']].sort_values('나이순위'))

    이름  나이  나이순위
5  강서준  45   1.0
2  박도윤  41   2.0
4  정하윤  38   3.0
7  윤지호  36   4.0
1  이서연  34   5.0
9  한도현  33   6.0
6  조예은  31   7.0
0  김민준  29   8.0
8  임수아  27   9.0
3  최지우  26  10.0

In [ ]:
# TODO 8 (위치 찾기·자료형): 급여가 가장 낮은 직원의 전체 정보를 idxmin()으로 찾고,
#         select_dtypes()로 문자열 컬럼만 따로 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.loc[df["급여"].idxmin()])
print(df.select_dtypes(include="object"))
```

</details>

In [176]:
# 코드 입력
print(df.loc[df["급여"].idxmin()])
print(df.select_dtypes(include = 'object'))

이름                최지우
나이                 26
부서                인사팀
직무                 HR
급여               3600
도시                 대구
부서평균급여    3733.333333
나이대            30세 이하
급여등급                하
나이순위             10.0
Name: 3, dtype: object
    이름    부서         직무  도시
0  김민준   개발팀  Developer  서울
1  이서연  마케팅팀   Marketer  부산
2  박도윤   개발팀  Developer  서울
3  최지우   인사팀         HR  대구
4  정하윤  마케팅팀   Marketer  서울
5  강서준   개발팀  Developer  인천
6  조예은   인사팀         HR  부산
7  윤지호  마케팅팀   Marketer  서울
8  임수아   개발팀  Developer  대구
9  한도현   인사팀         HR  서울

---

## 📝 실습 과제

In [ ]:
# 과제 1
# "도시" 컬럼의 값별 빈도수를 백분위 비율(%)로 확인하세요 (normalize=True 활용)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 1 답안

print(df["도시"].value_counts(normalize=True) * 100)
```

</details>

In [177]:
# 코드 입력
df.value_counts('도시', normalize = True)

도시
서울    0.5
대구    0.2
부산    0.2
인천    0.1
Name: proportion, dtype: float64

In [ ]:
# 과제 2
# "급여" 컬럼의 평균, 최댓값, 최솟값을 describe() 없이 직접 함수로 각각 구하세요
# (mean(), max(), min() 활용)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 2 답안

print("평균:", df["급여"].mean())
print("최댓값:", df["급여"].max())
print("최솟값:", df["급여"].min())
```

</details>

In [178]:
# 코드 입력
print(df['급여'].mean())
print(df['급여'].max())
print(df['급여'].min())

4340.0
6200
3600

In [ ]:
# 과제 3
# df.sample()을 이용해 무작위로 4개 행을 추출하되,
# random_state=1로 고정해서 다시 실행해도 같은 결과가 나오는지 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 3

sample1 = df.sample(n=4, random_state=1)
sample2 = df.sample(n=4, random_state=1)

print(sample1)
print(sample2)
```

</details>

In [179]:
# 코드 입력
print(df.sample(4))
print(df.sample(4, random_state = 1))

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급  나이순위
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상   4.0
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667  31 ~ 40세    하   5.0
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중   3.0
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중   8.0
    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급  나이순위
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상   2.0
9  한도현  33   인사팀         HR  3700  서울  3733.333333  31 ~ 40세    하   6.0
6  조예은  31   인사팀         HR  3900  부산  3733.333333  31 ~ 40세    하   7.0
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중   3.0

In [ ]:
# 과제 4
# 부서는 오름차순, 급여는 내림차순으로 다중 기준 정렬한 결과를 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 4 답안

df.sort_values(by=["부서", "급여"], ascending=[True, False])
```

</details>

In [182]:
# 코드 입력
df.sort_values(['부서', '급여'], ascending = [True, False])

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급  나이순위
5  강서준  45   개발팀  Developer  6200  인천  5000.000000    40세 이상    상   1.0
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상   2.0
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중   8.0
8  임수아  27   개발팀  Developer  4000  대구  5000.000000    30세 이하    중   9.0
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상   4.0
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중   3.0
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667  31 ~ 40세    하   5.0
6  조예은  31   인사팀         HR  3900  부산  3733.333333  31 ~ 40세    하   7.0
9  한도현  33   인사팀         HR  3700  서울  3733.333333  31 ~ 40세    하   6.0
3  최지우  26   인사팀         HR  3600  대구  3733.333333    30세 이하    하  10.0

In [ ]:
# 과제 5
# nlargest()를 이용해 나이가 가장 많은 상위 2명을 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df.nlargest(2, "나이")
```

</details>

In [183]:
# 코드 입력
print(df.nlargest(2, '나이'))

    이름  나이   부서         직무    급여  도시  부서평균급여     나이대 급여등급  나이순위
5  강서준  45  개발팀  Developer  6200  인천  5000.0  40세 이상    상   1.0
2  박도윤  41  개발팀  Developer  5600  서울  5000.0  40세 이상    상   2.0

---

## 📌 핵심 정리

- 미리보기: `head()`(앞), `tail()`(뒤), `sample()`(무작위)
- 구조 확인: `shape`(행렬 크기), `dtypes`(자료형), `info()`(종합 요약)
- 기술통계: `describe()`(수치형만), `describe(include='all')`(전체 컬럼)
- 결측치: `isnull()`/`isna()`(동일 함수) + `.sum()`으로 개수 집계
- 고유값: `unique()`(목록), `nunique()`(개수), `value_counts()`(값별 빈도)
- 정렬: `sort_values()`(값 기준), `sort_index()`(인덱스 기준), `nlargest()`/`nsmallest()`(상위·하위 N개)
- 순위·위치: `rank()`(순위 컬럼 생성), `idxmax()`/`idxmin()`(최댓값·최솟값의 행 인덱스)
- 자료형별 선택: `select_dtypes()`
- ⚠️ 대부분의 함수는 원본을 바꾸지 않고 새 결과를 반환 → 재할당 또는 `inplace=True` 필요

---

---

# 📘 CH07-02. 데이터 선택 (Indexing & Filtering)



## 🤔 먼저 생각해보기

> **인사팀 전체 명단에서 "개발팀이면서 급여가 4000 이상인 사람"만 뽑으려면 어떻게 해야 할까요?**

원하는 조건에 맞는 데이터만 정확히 골라내는 것은 데이터 분석에서 가장 기본이자 가장 자주 쓰이는 작업입니다. 이번 챕터에서는 Pandas로 원하는 행과 열을 정확히 골라내는 다양한 방법을 배웁니다.

---

## 📖 핵심 개념

이 챕터도 CH07-01과 동일한 직원 데이터를 사용합니다.

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박도윤", "최지우", "정하윤",
             "강서준", "조예은", "윤지호", "임수아", "한도현"],
    "나이": [29, 34, 41, 26, 38, 45, 31, 36, 27, 33],
    "부서": ["개발팀", "마케팅팀", "개발팀", "인사팀", "마케팅팀",
             "개발팀", "인사팀", "마케팅팀", "개발팀", "인사팀"],
    "직무": ["Developer", "Marketer", "Developer", "HR", "Marketer",
             "Developer", "HR", "Marketer", "Developer", "HR"],
    "급여": [4200, 3800, 5600, 3600, 4100, 6200, 3900, 4300, 4000, 3700],
    "도시": ["서울", "부산", "서울", "대구", "서울", "인천", "부산", "서울", "대구", "서울"]
}
df = pd.DataFrame(data)
```

</details>

In [83]:
# 코드 입력

import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박도윤", "최지우", "정하윤",
             "강서준", "조예은", "윤지호", "임수아", "한도현"],
    "나이": [29, 34, 41, 26, 38, 45, 31, 36, 27, 33],
    "부서": ["개발팀", "마케팅팀", "개발팀", "인사팀", "마케팅팀",
             "개발팀", "인사팀", "마케팅팀", "개발팀", "인사팀"],
    "직무": ["Developer", "Marketer", "Developer", "HR", "Marketer",
             "Developer", "HR", "Marketer", "Developer", "HR"],
    "급여": [4200, 3800, 5600, 3600, 4100, 6200, 3900, 4300, 4000, 3700],
    "도시": ["서울", "부산", "서울", "대구", "서울", "인천", "부산", "서울", "대구", "서울"]
}


df = pd.DataFrame(data)

### 1) 기본 컬럼 선택

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df["이름"])                 # 컬럼 1개 → Series
print(df[["이름", "급여"]])        # 컬럼 여러 개 → DataFrame (대괄호 두 번!)
```

</details>

In [84]:
# 코드 입력
print(df["이름"])
print(df[["이름", "급여"]])

0    김민준
1    이서연
2    박도윤
3    최지우
4    정하윤
5    강서준
6    조예은
7    윤지호
8    임수아
9    한도현
Name: 이름, dtype: object
    이름    급여
0  김민준  4200
1  이서연  3800
2  박도윤  5600
3  최지우  3600
4  정하윤  4100
5  강서준  6200
6  조예은  3900
7  윤지호  4300
8  임수아  4000
9  한도현  3700

### 2) `loc[]` — 라벨(이름) 기반 선택

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.loc[0])                    # 인덱스 라벨이 0인 행
print(df.loc[0:2])                   # ⚠️ loc의 슬라이싱은 끝(2)도 포함! (0,1,2행 모두 선택됨)
print(df.loc[0, "이름"])              # 0번 행, "이름" 컬럼의 값
print(df.loc[0:2, ["이름", "급여"]])   # 0~2행의 "이름","급여" 컬럼만
print(df.loc[:, "부서"])              # 모든 행의 "부서" 컬럼
```

</details>

In [89]:
# 코드 입력
#print(df.loc[0])
#print(df.loc[0:2]) # loc의 슬라이싱은 끝자리를 포함

#print(df.loc[0, "이름"])
#print(df.loc[0 : 2, ["이름", "급여"]])

print(df.loc[:, "부서"])

0     개발팀
1    마케팅팀
2     개발팀
3     인사팀
4    마케팅팀
5     개발팀
6     인사팀
7    마케팅팀
8     개발팀
9     인사팀
Name: 부서, dtype: object

### 3) `iloc[]` — 정수 위치(순서) 기반 선택

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.iloc[0])                    # 0번째 위치의 행
print(df.iloc[0:2])                   # ⚠️ iloc의 슬라이싱은 끝(2) 미포함! (0,1행만 선택됨)
print(df.iloc[0, 0])                   # 0번째 행, 0번째 열의 값
print(df.iloc[0:3, [0, 4]])            # 0~2번째 행의, 0번째·4번째 열
print(df.iloc[-1])                     # 마지막 행 (음수 인덱스도 사용 가능)
```

</details>

In [ ]:
# 코드 입력
#print(df.iloc[0])
#print(df.iloc[0 : 2]) # iloc에서는 끝자리를 포함하지 않는다

#print(df.iloc[0, 0])
#print(df.iloc[0 : 2, [0, 4]])
print(df.iloc[-1])

    이름    급여
0  김민준  4200
1  이서연  3800
이름     한도현
나이      33
부서     인사팀
직무      HR
급여    3700
도시      서울
Name: 9, dtype: object

### 4) 서로 다른 방식 비교 — `loc[]` vs `iloc[]`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 인덱스가 기본 정수(0,1,2,...)일 때는 헷갈릴 수 있지만, 라벨을 직접 지정하면 차이가 명확해짐
df_named = df.set_index("이름")   # "이름"을 인덱스로 지정

print(df_named.loc["김민준"])       # ✅ "김민준"이라는 라벨(이름)로 조회
# print(df_named.iloc["김민준"])    # ❌ iloc은 정수 위치만 받으므로 에러!
print(df_named.iloc[0])              # ✅ 0번째 위치(=김민준의 행)로 조회
```

</details>

In [98]:
# 코드 입력
df_named = df.set_index('이름')
df_named

print(df_named.loc['김민준'])
print(df_named.iloc[0])

나이           29
부서          개발팀
직무    Developer
급여         4200
도시           서울
Name: 김민준, dtype: object
나이           29
부서          개발팀
직무    Developer
급여         4200
도시           서울
Name: 김민준, dtype: object

| 구분 | `loc[]` | `iloc[]` |
|---|---|---|
| 기준 | 인덱스 라벨(이름) | 정수 위치(순서) |
| 슬라이싱 끝 포함 여부 | **포함** (`0:2`는 0,1,2) | **미포함** (`0:2`는 0,1만) |
| 조건식 사용 | 가능 (`df.loc[df["급여"]>4000]`) | 불가능 |
| 인덱스가 문자열일 때 | 그 문자열로 바로 접근 가능 | 여전히 숫자 위치로만 접근 |

> 💡 **핵심 요약**: 이름표(라벨)로 찾고 싶으면 `loc`, 순서(몇 번째)로 찾고 싶으면 `iloc`을 사용하세요. 특히 **슬라이싱 시 끝 포함 여부가 다르다**는 점이 가장 헷갈리는 포인트이니 꼭 기억하세요.

### 5) 조건부 필터링 (Boolean Indexing)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df[df["급여"] > 4000])          # 급여가 4000 초과인 행만
print(df[df["부서"] == "개발팀"])       # 부서가 개발팀인 행만
```

</details>

In [99]:
# 코드 입력

# 급여 4000 초과
print(df[df['급여'] > 4000])
# 부서가 개발팀인 행만 출력
print(df[df['부서'] == '개발팀'])

    이름  나이    부서         직무    급여  도시
0  김민준  29   개발팀  Developer  4200  서울
2  박도윤  41   개발팀  Developer  5600  서울
4  정하윤  38  마케팅팀   Marketer  4100  서울
5  강서준  45   개발팀  Developer  6200  인천
7  윤지호  36  마케팅팀   Marketer  4300  서울
    이름  나이   부서         직무    급여  도시
0  김민준  29  개발팀  Developer  4200  서울
2  박도윤  41  개발팀  Developer  5600  서울
5  강서준  45  개발팀  Developer  6200  인천
8  임수아  27  개발팀  Developer  4000  대구

### 6) 다중 조건 필터링 — `&`(and), `|`(or), `~`(not)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 여러 조건을 동시에 사용할 땐 & / | 를 쓰고, 각 조건은 반드시 괄호로 감싸야 함
print(df[(df["부서"] == "개발팀") & (df["급여"] >= 4000)])    # 개발팀 이면서 급여 4000 이상
print(df[(df["부서"] == "개발팀") | (df["부서"] == "인사팀")])  # 개발팀 또는 인사팀
print(df[~(df["부서"] == "개발팀")])                              # 개발팀이 아닌 사람 (부정)
```

</details>

In [104]:
# 코드 입력
# 여러 조건을 동시에 사용할 땐 & / | 를 쓰고, 각 조건은 반드시 괄호로 감싸야 함

# 부서는 개발팀이면서 급여는 4000 이상
print(df[(df['부서'] == '개발팀') & (df['급여'] >= 4000)])

# 부서가 개발팀 혹은 인사팀
print(df[(df['부서'] == '개발팀') | (df['부서'] == "인사팀")])

# 부서가 개발팀이 아님
print(df[~(df['부서'] == '개발팀')])

    이름  나이   부서         직무    급여  도시
0  김민준  29  개발팀  Developer  4200  서울
2  박도윤  41  개발팀  Developer  5600  서울
5  강서준  45  개발팀  Developer  6200  인천
8  임수아  27  개발팀  Developer  4000  대구
    이름  나이   부서         직무    급여  도시
0  김민준  29  개발팀  Developer  4200  서울
2  박도윤  41  개발팀  Developer  5600  서울
3  최지우  26  인사팀         HR  3600  대구
5  강서준  45  개발팀  Developer  6200  인천
6  조예은  31  인사팀         HR  3900  부산
8  임수아  27  개발팀  Developer  4000  대구
9  한도현  33  인사팀         HR  3700  서울
    이름  나이    부서        직무    급여  도시
1  이서연  34  마케팅팀  Marketer  3800  부산
3  최지우  26   인사팀        HR  3600  대구
4  정하윤  38  마케팅팀  Marketer  4100  서울
6  조예은  31   인사팀        HR  3900  부산
7  윤지호  36  마케팅팀  Marketer  4300  서울
9  한도현  33   인사팀        HR  3700  서울

> ⚠️ 파이썬의 `and`/`or`/`not`은 Series(여러 값)에는 사용할 수 없습니다. 반드시 `&`/`|`/`~`를 사용해야 하며, 각 조건은 괄호로 묶어야 연산 우선순위 문제가 생기지 않습니다.

### 7) 주요 필터링 메서드 — `isin()`, `between()`, `str.contains()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# isin(): 여러 값 중 하나라도 일치하는지 확인 (여러 개의 == 조건을 or로 묶는 것과 같은 효과)
print(df[df["도시"].isin(["서울", "부산"])])
```

</details>

In [ ]:
# isin()
# 여러 값 중 하나라도 일치하는지 확인
# (여러 개의 == 조건을 or로 묶는 것과 같은 효과)

print(df[df['도시'].isin(["서울", "부산"])])

    이름  나이    부서         직무    급여  도시
0  김민준  29   개발팀  Developer  4200  서울
1  이서연  34  마케팅팀   Marketer  3800  부산
2  박도윤  41   개발팀  Developer  5600  서울
4  정하윤  38  마케팅팀   Marketer  4100  서울
6  조예은  31   인사팀         HR  3900  부산
7  윤지호  36  마케팅팀   Marketer  4300  서울
9  한도현  33   인사팀         HR  3700  서울

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# between(): 범위 안에 있는지 확인 (양쪽 끝 값 포함)
print(df[df["나이"].between(30, 40)])   # 30살 이상 40살 이하
```

</details>

In [106]:
# between()
# 범위 안에 있는지 확인 (양쪽 끝 값 포함)

print(df[df['나이'].between(30, 40)])

    이름  나이    부서        직무    급여  도시
1  이서연  34  마케팅팀  Marketer  3800  부산
4  정하윤  38  마케팅팀  Marketer  4100  서울
6  조예은  31   인사팀        HR  3900  부산
7  윤지호  36  마케팅팀  Marketer  4300  서울
9  한도현  33   인사팀        HR  3700  서울

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# str.contains(): 문자열에 특정 단어가 포함되어 있는지 확인
print(df[df["직무"].str.contains("Dev")])   # "Dev"가 포함된 직무 (Developer)
```

</details>

In [107]:
# str.contains(): 문자열에 특정 단어가 포함되어 있는지 확인
# "Dev"가 포함된 직무 (Developer)

print(df[df['직무'].str.contains("Dev")])

    이름  나이   부서         직무    급여  도시
0  김민준  29  개발팀  Developer  4200  서울
2  박도윤  41  개발팀  Developer  5600  서울
5  강서준  45  개발팀  Developer  6200  인천
8  임수아  27  개발팀  Developer  4000  대구

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 여러 필터링 방법을 조합할 수도 있음
print(df[(df["도시"].isin(["서울", "인천"])) & (df["나이"].between(25, 35))])
```

</details>

In [109]:
# 여러 필터링 방법을 조합할 수도 있음

# 도시는 서울 또는 인천, 나이는 25 ~ 35
print(df[(df['도시'].isin(['서울', '인천'])) & (df['나이'].between(25, 35))])

    이름  나이   부서         직무    급여  도시
0  김민준  29  개발팀  Developer  4200  서울
9  한도현  33  인사팀         HR  3700  서울

### 8) 단일 값 빠르게 접근 — `at[]`, `iat[]`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.at[0, "이름"])      # 인덱스 라벨 0의 "이름" 값 (라벨 기준, 값 1개)
print(df.iat[0, 0])          # 0번째 행, 0번째 열의 값 (위치 기준, 값 1개)

df.at[0, "급여"] = 4300      # 값 수정도 가능
print(df.loc[0])
```

</details>

In [116]:
# 코드 입력

print(df.at[0, "이름"])
print(df.iat[0, 2])

df.at[0, "급여"] = 4300
df.loc[0]

김민준
개발팀

이름          김민준
나이           29
부서          개발팀
직무    Developer
급여         4300
도시           서울
Name: 0, dtype: object

> 💡 `loc`/`iloc`는 여러 행·열을 한 번에 선택할 수 있는 반면, `at`/`iat`는 "정확히 값 하나"만 가져오거나 바꿀 때 사용합니다. 값 하나만 다룰 때는 `at`/`iat`가 더 빠르고 의도도 명확합니다.

### 9) 인덱스 재설정 — `set_index()`, `reset_index()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df_named = df.set_index("이름")       # "이름" 컬럼을 인덱스로 사용
print(df_named.loc["김민준"])          # 이름으로 바로 조회 가능

df_reset = df_named.reset_index()     # 다시 기본 정수 인덱스(0,1,2...)로 되돌림
print(df_reset.head())
```

</details>

In [119]:
# 코드 입력

df_named = df.set_index('이름')
df_named

df_reset = df_named.reset_index()
df_reset

    이름  나이    부서         직무    급여  도시
0  김민준  29   개발팀  Developer  4300  서울
1  이서연  34  마케팅팀   Marketer  3800  부산
2  박도윤  41   개발팀  Developer  5600  서울
3  최지우  26   인사팀         HR  3600  대구
4  정하윤  38  마케팅팀   Marketer  4100  서울
5  강서준  45   개발팀  Developer  6200  인천
6  조예은  31   인사팀         HR  3900  부산
7  윤지호  36  마케팅팀   Marketer  4300  서울
8  임수아  27   개발팀  Developer  4000  대구
9  한도현  33   인사팀         HR  3700  서울

> 💡 `set_index()`로 의미 있는 컬럼(사번, 이름 등)을 인덱스로 지정하면 `loc[]`로 이름 기반 조회가 가능해져 코드가 더 직관적입니다. `reset_index()`는 필터링·그룹 연산 후 인덱스가 뒤섞였을 때 `drop=True` 옵션과 함께 정리 용도로 자주 사용합니다.

### 10) 문자열로 조건 작성하기 — `query()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.query("급여 >= 4000"))                       # 조건을 문자열로 작성
print(df.query("부서 == '개발팀' and 나이 < 40"))       # and/or를 그대로 사용 가능

salary_cut = 4000
print(df.query("급여 >= @salary_cut"))                 # 파이썬 변수는 @로 참조
```

</details>

In [ ]:
# 코드 입력
print(df.query('급여 >= 4000'))
print(df.query("부서 == '개발팀' and 나이 < 40"))

    이름  나이    부서         직무    급여  도시
0  김민준  29   개발팀  Developer  4300  서울
2  박도윤  41   개발팀  Developer  5600  서울
4  정하윤  38  마케팅팀   Marketer  4100  서울
5  강서준  45   개발팀  Developer  6200  인천
7  윤지호  36  마케팅팀   Marketer  4300  서울
8  임수아  27   개발팀  Developer  4000  대구
    이름  나이   부서         직무    급여  도시
0  김민준  29  개발팀  Developer  4300  서울
8  임수아  27  개발팀  Developer  4000  대구

> 💡 `query()`는 `&`/`|` 대신 `and`/`or`를 그대로 쓸 수 있어서 조건이 여러 개일 때 가독성이 좋습니다. 외부 변수를 조건에 넣을 때는 반드시 변수명 앞에 `@`를 붙여야 합니다.
>
> ⚠️ 컬럼명에 공백이나 특수문자가 있으면 백틱(`` ` ``)으로 감싸야 합니다. 예: `` df.query("`부서 명` == '개발팀'") ``

---

## ⚠️ 자주 하는 실수

> ⚠️ `loc`와 `iloc`의 슬라이싱 끝 포함 여부를 혼동해서 예상보다 한 개 많거나 적은 행을 가져오는 경우가 매우 흔합니다.

> ⚠️ 다중 조건에서 `and`/`or`를 그대로 써서 `ValueError: The truth value of a Series is ambiguous`가 발생하는 경우가 흔합니다. (&, |)

> ⚠️ 조건을 괄호로 감싸지 않아서 연산자 우선순위 문제로 예상과 다른 결과가 나오는 경우가 있습니다.

> ⚠️ `query()`에서 외부 변수를 `@` 없이 그대로 쓰면 컬럼명으로 착각해 에러가 나거나, 문자열 값에 따옴표를 빠뜨려 문법 오류가 나는 경우가 흔합니다.

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# df[df["부서"] == "개발팀" & df["급여"] >= 4000]   # ❌ 괄호 없어서 에러/오작동
df[(df["부서"] == "개발팀") & (df["급여"] >= 4000)]    # ✅ 각 조건을 괄호로 감쌈
```

</details>

In [ ]:
# 코드 입력

# df[df["부서"] == "개발팀" & df["급여"] >= 4000]   # ❌ 괄호 없어서 에러/오작동
df[(df["부서"] == "개발팀") & (df["급여"] >= 4000)]    # ✅ 각 조건을 괄호로 감쌈

---

## 🚀 실무에서는?

> 🚀 실무 데이터 분석의 대부분은 "전체 데이터에서 특정 조건에 맞는 부분만 뽑아서 살펴보는" 작업의 연속입니다. `loc`/`iloc`와 조건 필터링은 이후 나올 전처리, 그룹 분석, 시각화 전 단계에서 항상 함께 사용됩니다. 조건이 복잡해질수록 `&`/`|` 조합보다 `query()`로 작성하는 편이 코드 가독성이 좋아지는 경우가 많습니다.

---

## 🧩 Check Point

**Q1.** `df.loc[0:2]`와 `df.iloc[0:2]`의 결과 행 개수 차이는? ① 둘 다 2개 ② 둘 다 3개 ③ loc는 3개, iloc는 2개 ④ loc는 2개, iloc는 3개
<details><summary>정답</summary>③ loc는 3개(끝 포함), iloc는 2개(끝 미포함)</details>

**Q2.** 여러 값 중 하나라도 일치하는지 확인할 때 사용하는 메서드는? ① between() ② isin() ③ contains() ④ query()
<details><summary>정답</summary>② isin()</details>

**Q3.** 값 하나만 빠르게 읽거나 수정하고 싶을 때 가장 적합한 방법은? ① loc[] ② iloc[] ③ at[]/iat[] ④ query()
<details><summary>정답</summary>③ at[]/iat[]</details>

**Q4.** `query()` 조건식 안에서 파이썬 변수를 참조하려면 변수명 앞에 무엇을 붙여야 하나요? ① `$` ② `#` ③ `@` ④ `%`
<details><summary>정답</summary>③ `@`</details>

---

## 💻 실습

> 🔧 아래 코드 블록은 ipynb 셀로 그대로 변환됩니다. 난이도가 단계적으로 올라갑니다.

In [ ]:
# TODO 1 (loc/iloc 기본)
# loc으로 0~2번 행의 "이름","부서"를, iloc으로 같은 위치를 각각 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.loc[0:2, ["이름", "부서"]])
print(df.iloc[0:3, [0, 2]])
```

</details>

In [145]:
# 코드 입력
print(df.loc[0 : 2], ["이름", "부서"])
print(df.iloc[0 : 3, [0, 2]])

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667  31 ~ 40세    하
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상 ['이름', '부서']
    이름    부서
0  김민준   개발팀
1  이서연  마케팅팀
2  박도윤   개발팀

In [ ]:
# TODO 2 (조건 필터링)
# 급여가 4500 이상인 직원만 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df[df["급여"] >= 4500])
```

</details>

In [146]:
# 코드 입력
print(df[df['급여'] >= 4500])

    이름  나이   부서         직무    급여  도시  부서평균급여     나이대 급여등급
2  박도윤  41  개발팀  Developer  5600  서울  5000.0  40세 이상    상
5  강서준  45  개발팀  Developer  6200  인천  5000.0  40세 이상    상

In [ ]:
# TODO 3 (다중 조건)
# 마케팅팀이면서 나이가 35세 이하인 직원을 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df[(df["부서"] == "마케팅팀") & (df["나이"] <= 35)])
```

</details>

In [149]:
# 코드 입력
print(df[(df['부서'] == '마케팅팀') & (df['나이'] <= 35)])

    이름  나이    부서        직무    급여  도시       부서평균급여       나이대 급여등급
1  이서연  34  마케팅팀  Marketer  3800  부산  4066.666667  31 ~ 40세    하

In [ ]:
# TODO 4 (isin)
# 도시가 "서울" 또는 "대구"인 직원만 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df[df["도시"].isin(["서울", "대구"])])
```

</details>

In [150]:
# 코드 입력

df[df['도시'].isin(['서울', '대구'])]

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
3  최지우  26   인사팀         HR  3600  대구  3733.333333    30세 이하    하
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상
8  임수아  27   개발팀  Developer  4000  대구  5000.000000    30세 이하    중
9  한도현  33   인사팀         HR  3700  서울  3733.333333  31 ~ 40세    하

In [ ]:
# TODO 5 (between)
# 나이가 28~40세 사이인 직원만 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df[df["나이"].between(28, 40)])
```

</details>

In [151]:
# 코드 입력

df[df['나이'].between(28, 40)]

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667  31 ~ 40세    하
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중
6  조예은  31   인사팀         HR  3900  부산  3733.333333  31 ~ 40세    하
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상
9  한도현  33   인사팀         HR  3700  서울  3733.333333  31 ~ 40세    하

In [ ]:
# TODO 6 (str.contains)
# 직무에 "Market"이 포함된 직원만 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df[df["직무"].str.contains("Market")])
```

</details>

In [153]:
# 코드 입력

df[df['직무'].str.contains("Market")]

    이름  나이    부서        직무    급여  도시       부서평균급여       나이대 급여등급
1  이서연  34  마케팅팀  Marketer  3800  부산  4066.666667  31 ~ 40세    하
4  정하윤  38  마케팅팀  Marketer  4100  서울  4066.666667  31 ~ 40세    중
7  윤지호  36  마케팅팀  Marketer  4300  서울  4066.666667  31 ~ 40세    상

In [ ]:
# TODO 7 (at/iat): 0번 인덱스 직원의 "부서" 값을 at[]으로 확인하고,
# 같은 값을 iat[]으로도 확인하세요 (열 위치는 직접 세어보세요)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.at[0, "부서"])
print(df.iat[0, 2])   # 컬럼 순서: 이름(0),나이(1),부서(2)...
```

</details>

In [155]:
# 코드 입력

print(df.at[0, '부서'])
print(df.iat[0, 2])

개발팀
개발팀

In [ ]:
# TODO 8 (인덱스 재설정)
# "이름"을 인덱스로 설정한 뒤 "박도윤"의 정보를 loc[]으로 조회하고,
# reset_index()로 다시 기본 인덱스로 되돌리세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
df_named = df.set_index("이름")
print(df_named.loc["박도윤"])
print(df_named.reset_index().head())
```

</details>

In [156]:
# 코드 입력
indexed = df.set_index('이름')
print(indexed.loc["박도윤"])

reset = indexed.reset_index()
print(reset)

나이               41
부서              개발팀
직무        Developer
급여             5600
도시               서울
부서평균급여       5000.0
나이대          40세 이상
급여등급              상
Name: 박도윤, dtype: object
    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667  31 ~ 40세    하
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
3  최지우  26   인사팀         HR  3600  대구  3733.333333    30세 이하    하
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중
5  강서준  45   개발팀  Developer  6200  인천  5000.000000    40세 이상    상
6  조예은  31   인사팀         HR  3900  부산  3733.333333  31 ~ 40세    하
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상
8  임수아  27   개발팀  Developer  4000  대구  5000.000000    30세 이하    중
9  한도현  33   인사팀         HR  3700  서울  3733.333333  31 ~ 40세    하

In [ ]:
# TODO 9 (query)
# query()를 이용해 급여가 4000 이상이면서 도시가 "서울"인 직원을 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.query("급여 >= 4000 and 도시 == '서울'"))
```

</details>

In [158]:
# 코드 입력

df.query("급여 >= 4000 and 도시 == '서울'")

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
0  김민준  29   개발팀  Developer  4200  서울  5000.000000    30세 이하    중
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상

---

## 📝 실습 과제

In [ ]:
# 과제 1
# 개발팀이 아니면서(~ 활용) 급여가 4000 이상인 직원을 선택하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 1 답안

df[(df["부서"] != "개발") & (df["급여"] >= 4000)]
```

</details>

In [159]:
# 코드 입력
df[~(df['부서'] == '개발팀') & (df['급여'] >= 4000)]

    이름  나이    부서        직무    급여  도시       부서평균급여       나이대 급여등급
4  정하윤  38  마케팅팀  Marketer  4100  서울  4066.666667  31 ~ 40세    중
7  윤지호  36  마케팅팀  Marketer  4300  서울  4066.666667  31 ~ 40세    상

In [ ]:
# 과제 2
# 나이가 30세 미만이거나 급여가 6000 이상인 직원을 선택하세요 (| 활용)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df[(df["나이"] < 30) | (df["급여"] >= 6000)]
```

</details>

In [160]:
# 코드 입력
df[(df['나이'] < 30) | (df['급여'] >= 6000)]

    이름  나이   부서         직무    급여  도시       부서평균급여     나이대 급여등급
0  김민준  29  개발팀  Developer  4200  서울  5000.000000  30세 이하    중
3  최지우  26  인사팀         HR  3600  대구  3733.333333  30세 이하    하
5  강서준  45  개발팀  Developer  6200  인천  5000.000000  40세 이상    상
8  임수아  27  개발팀  Developer  4000  대구  5000.000000  30세 이하    중

In [ ]:
# 과제 3
# 도시가 "서울"인 직원 중, iloc으로 처음 2명만 선택하세요 (조건 필터링 + iloc 조합)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df[df["도시"] == "서울"].iloc[:2]
```

</details>

In [162]:
# 코드 입력
df[df['도시'] == '서울'].iloc[0:2]

    이름  나이   부서         직무    급여  도시  부서평균급여     나이대 급여등급
0  김민준  29  개발팀  Developer  4200  서울  5000.0  30세 이하    중
2  박도윤  41  개발팀  Developer  5600  서울  5000.0  40세 이상    상

In [ ]:
# 과제 4
# query()와 @ 변수를 사용해 나이가 기준값(예: 35) 이상인 직원을 조회하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
age = 35

df.query("나이 >= @age")
```

</details>

In [163]:
# 코드 입력
age = 35

df.query("나이 > @age")

    이름  나이    부서         직무    급여  도시       부서평균급여       나이대 급여등급
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000    40세 이상    상
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667  31 ~ 40세    중
5  강서준  45   개발팀  Developer  6200  인천  5000.000000    40세 이상    상
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667  31 ~ 40세    상

In [ ]:
# 과제 5
# "도시"를 인덱스로 설정한 뒤, "서울"에 해당하는 모든 행을 loc[]으로 선택하세요 (중복 라벨 선택 결과 확인)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df.set_index("도시").loc["서울"]
```

</details>

In [164]:
# 코드 입력

df.set_index('도시').loc['서울']

     이름  나이    부서         직무    급여       부서평균급여       나이대 급여등급
도시
서울  김민준  29   개발팀  Developer  4200  5000.000000    30세 이하    중
서울  박도윤  41   개발팀  Developer  5600  5000.000000    40세 이상    상
서울  정하윤  38  마케팅팀   Marketer  4100  4066.666667  31 ~ 40세    중
서울  윤지호  36  마케팅팀   Marketer  4300  4066.666667  31 ~ 40세    상
서울  한도현  33   인사팀         HR  3700  3733.333333  31 ~ 40세    하

---

## 📌 핵심 정리

- 컬럼 선택: `df["컬럼"]`(Series) vs `df[["컬럼"]]`(DataFrame)
- `loc[]`: 라벨 기준, 슬라이싱 끝 포함 / `iloc[]`: 위치 기준, 슬라이싱 끝 미포함
- 조건 필터링: `df[조건]`, 다중 조건은 `&`(and)/`|`(or)/`~`(not) + 괄호 필수
- `isin()`: 여러 값 중 일치 확인 / `between()`: 범위 확인 / `str.contains()`: 문자열 포함 확인
- 단일 값 접근: `at[]`(라벨), `iat[]`(위치) — 값 하나를 빠르게 읽거나 수정
- 인덱스 관리: `set_index()`(의미 있는 컬럼을 인덱스로), `reset_index()`(기본 인덱스로 복원)
- `query()`: 조건을 문자열로 작성, `and`/`or` 사용 가능, 외부 변수는 `@`로 참조

---

---

# 📘 CH07-03. 그룹 분석 (Aggregation & Transformation)

## 🤔 먼저 생각해보기

> **회사 전체 평균 급여가 아니라, "부서별" 평균 급여를 알고 싶다면 어떻게 나눠서 계산해야 할까요?**

전체를 한 번에 계산하는 대신, 특정 기준(부서, 직무 등)으로 데이터를 그룹으로 쪼갠 뒤 각 그룹마다 통계를 계산하는 작업을 **그룹 분석**이라고 합니다. 이는 데이터 분석에서 시각화 전에 가장 많이 쓰이는 과정 중 하나입니다.

---

## 📖 핵심 개념

이전 소단원과 동일한 직원 데이터를 사용합니다.

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박도윤", "최지우", "정하윤",
             "강서준", "조예은", "윤지호", "임수아", "한도현"],
    "나이": [29, 34, 41, 26, 38, 45, 31, 36, 27, 33],
    "부서": ["개발팀", "마케팅팀", "개발팀", "인사팀", "마케팅팀",
             "개발팀", "인사팀", "마케팅팀", "개발팀", "인사팀"],
    "직무": ["Developer", "Marketer", "Developer", "HR", "Marketer",
             "Developer", "HR", "Marketer", "Developer", "HR"],
    "급여": [4200, 3800, 5600, 3600, 4100, 6200, 3900, 4300, 4000, 3700],
    "도시": ["서울", "부산", "서울", "대구", "서울", "인천", "부산", "서울", "대구", "서울"]
}
df = pd.DataFrame(data)
```

</details>

In [123]:
# 코드 입력

import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박도윤", "최지우", "정하윤",
             "강서준", "조예은", "윤지호", "임수아", "한도현"],
    "나이": [29, 34, 41, 26, 38, 45, 31, 36, 27, 33],
    "부서": ["개발팀", "마케팅팀", "개발팀", "인사팀", "마케팅팀",
             "개발팀", "인사팀", "마케팅팀", "개발팀", "인사팀"],
    "직무": ["Developer", "Marketer", "Developer", "HR", "Marketer",
             "Developer", "HR", "Marketer", "Developer", "HR"],
    "급여": [4200, 3800, 5600, 3600, 4100, 6200, 3900, 4300, 4000, 3700],
    "도시": ["서울", "부산", "서울", "대구", "서울", "인천", "부산", "서울", "대구", "서울"]
}

df = pd.DataFrame(data)

### 1) `groupby()` 기초 — 기준별로 데이터 쪼개기

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
grouped = df.groupby("부서")     # 부서를 기준으로 그룹을 나눔 (아직 계산은 안 함)
print(grouped)                     # <pandas...DataFrameGroupBy object> ← 계산 전에는 이렇게만 보임

print(grouped["급여"].mean())    # 부서별 급여 평균
# 부서
# 개발팀     5000.0
# 마케팅팀   4066.666667
# 인사팀     3733.333333
```

</details>

In [125]:
# 부서를 기준으로 그룹을 나눔 (아직 계산은 안 함)

grouped = df.groupby('부서')
print(grouped)

print(grouped['급여'].mean())

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000012952071040>
부서
개발팀     5000.000000
마케팅팀    4066.666667
인사팀     3733.333333
Name: 급여, dtype: float64

> 💡 `groupby()`는 그 자체로는 계산을 하지 않고, "이렇게 나누겠다"는 준비 단계만 수행합니다. 뒤에 `.mean()`, `.sum()` 같은 집계 함수를 붙여야 실제 계산이 이뤄집니다.

### 2) 단일/다중 집계 함수

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.groupby("부서")["급여"].mean())      # 평균
print(df.groupby("부서")["급여"].sum())        # 합계
print(df.groupby("부서")["급여"].count())      # 개수(결측치 제외)
print(df.groupby("부서")["급여"].median())     # 중앙값
print(df.groupby("부서")["급여"].max())        # 최댓값
print(df.groupby("부서")["급여"].min())        # 최솟값
```

</details>

In [126]:
# 코드 입력
print(df.groupby('부서')['급여'].mean())

print(df.groupby('부서')['급여'].sum())

print(df.groupby('부서')['급여'].count())

print(df.groupby('부서')['급여'].median())

print(df.groupby('부서')['급여'].max())

print(df.groupby('부서')['급여'].min())

부서
개발팀     5000.000000
마케팅팀    4066.666667
인사팀     3733.333333
Name: 급여, dtype: float64
부서
개발팀     20000
마케팅팀    12200
인사팀     11200
Name: 급여, dtype: int64
부서
개발팀     4
마케팅팀    3
인사팀     3
Name: 급여, dtype: int64
부서
개발팀     4900.0
마케팅팀    4100.0
인사팀     3700.0
Name: 급여, dtype: float64
부서
개발팀     6200
마케팅팀    4300
인사팀     3900
Name: 급여, dtype: int64
부서
개발팀     4000
마케팅팀    3800
인사팀     3600
Name: 급여, dtype: int64

**여러 컬럼, 여러 기준으로 그룹화**

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.groupby("부서")[["급여", "나이"]].mean())    # 여러 컬럼을 동시에 집계

print(df.groupby(["부서", "직무"])["급여"].mean())    # 두 가지 기준으로 동시에 그룹화
# 부서      직무
# 개발팀    Developer    5266.666667
# 마케팅팀  Marketer     4066.666667
# 인사팀    HR           3733.333333
```

</details>

In [128]:
# 코드 입력
print(df.groupby('부서')[['급여', '나이']].mean())

print(df.groupby(['부서', '직무'])[['급여']].mean())

               급여    나이
부서
개발팀   5000.000000  35.5
마케팅팀  4066.666667  36.0
인사팀   3733.333333  30.0
                         급여
부서   직무
개발팀  Developer  5000.000000
마케팅팀 Marketer   4066.666667
인사팀  HR         3733.333333

### 3) `agg()`(`aggregate()`) — 여러 통계를 한 번에

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.groupby("부서")["급여"].agg(["mean", "sum", "max"]))   # 평균/합계/최댓값을 한 번에
#          mean    sum   max
# 부서
# 개발팀   5000.0  20000  6200
# ...
```

</details>

In [130]:
# 평균/합계/최댓값을 한 번에
print(df.groupby('부서')['급여'].agg(['mean', 'sum', 'max']))

             mean    sum   max
부서
개발팀   5000.000000  20000  6200
마케팅팀  4066.666667  12200  4300
인사팀   3733.333333  11200  3900

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 컬럼마다 다른 집계 함수를 적용하고 싶을 때 — 딕셔너리 사용
print(df.groupby("부서").agg({
    "나이": "mean",
    "급여": "sum"
}))
#          나이       급여
# 부서
# 개발팀   36.25    20000
# 마케팅팀 36.00    12200
# 인사팀   32.00    11200
```

</details>

In [132]:
# 컬럼마다 다른 집계 함수를 적용하고 싶을 때 — 딕셔너리 사용
print(df.groupby('부서').agg({
    '나이' : 'mean',
    '급여' : 'sum',
}))

        나이     급여
부서
개발팀   35.5  20000
마케팅팀  36.0  12200
인사팀   30.0  11200

### 4) `transform()`과 `filter()` — 그룹별 변환·필터링

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# transform(): 그룹별 계산 결과를 "원본과 같은 행 개수"로 되돌려줌 (원본에 새 컬럼으로 붙이기 좋음)
df["부서평균급여"] = df.groupby("부서")["급여"].transform("mean")
print(df[["이름", "부서", "급여", "부서평균급여"]])
```

</details>

In [134]:
# transform()
# 그룹별 계산 결과를 "원본과 같은 행 개수"로 되돌려줌
# (원본에 새 컬럼으로 붙이기 좋음)

df['부서평균급여'] = df.groupby('부서')['급여'].transform('mean')
df

    이름  나이    부서         직무    급여  도시       부서평균급여
0  김민준  29   개발팀  Developer  4200  서울  5000.000000
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000
3  최지우  26   인사팀         HR  3600  대구  3733.333333
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667
5  강서준  45   개발팀  Developer  6200  인천  5000.000000
6  조예은  31   인사팀         HR  3900  부산  3733.333333
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667
8  임수아  27   개발팀  Developer  4000  대구  5000.000000
9  한도현  33   인사팀         HR  3700  서울  3733.333333

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# filter(): 조건을 만족하는 "그룹 전체"를 통째로 선택 (그룹 평균이 4000 이상인 부서만)
result = df.groupby("부서").filter(lambda x: x["급여"].mean() >= 4000)
print(result)
```

</details>

In [135]:
# filter()
# 조건을 만족하는 "그룹 전체"를 통째로 선택
# (그룹 평균이 4000 이상인 부서만)

result = df.groupby('부서').filter(lambda x: x['급여'].mean() >= 4000)
print(result)

    이름  나이    부서         직무    급여  도시       부서평균급여
0  김민준  29   개발팀  Developer  4200  서울  5000.000000
1  이서연  34  마케팅팀   Marketer  3800  부산  4066.666667
2  박도윤  41   개발팀  Developer  5600  서울  5000.000000
4  정하윤  38  마케팅팀   Marketer  4100  서울  4066.666667
5  강서준  45   개발팀  Developer  6200  인천  5000.000000
7  윤지호  36  마케팅팀   Marketer  4300  서울  4066.666667
8  임수아  27   개발팀  Developer  4000  대구  5000.000000

### 5) 교차표와 피벗 테이블 — `pd.crosstab()`, `pivot_table()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# crosstab(): 두 범주형 컬럼의 조합별 "개수"를 표로 (기본은 빈도수)
print(pd.crosstab(df["부서"], df["도시"]))
#         대구  부산  서울  인천
# 부서
# 개발팀     1     0     2     1
# 마케팅팀   0     1     2     0
# 인사팀     0     1     2     0
```

</details>

In [137]:
# crosstab()
# 두 범주형 컬럼의 조합별 "개수"를 표로 (기본은 빈도수)

pd.crosstab(df['부서'], df['도시'])

도시    대구  부산  서울  인천
부서
개발팀    1   0   2   1
마케팅팀   0   1   2   0
인사팀    1   1   1   0

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# pivot_table(): groupby처럼 통계 계산도 가능한 더 유연한 표 (기본 집계는 평균)
print(df.pivot_table(index="부서", columns="직무", values="급여"))
#           Developer  HR      Marketer
# 부서
# 개발팀      5266.67    NaN      NaN
# 마케팅팀    NaN         NaN     4066.67
# 인사팀      NaN         3733.33  NaN
```

</details>

In [138]:
# pivot_table()
# groupby처럼 통계 계산도 가능한 더 유연한 표 (기본 집계는 평균)

df.pivot_table(index = '부서', columns = '직무', values = '급여')

직무    Developer           HR     Marketer
부서
개발팀      5000.0          NaN          NaN
마케팅팀        NaN          NaN  4066.666667
인사팀         NaN  3733.333333          NaN

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(df.pivot_table(index="부서", values="급여", aggfunc=["mean", "count"]))   # 집계 함수 직접 지정
```

</details>

In [139]:
# 집계 함수 직접 지정

df.pivot_table(index = '부서', columns = '직무', values = '급여', aggfunc = ['mean', 'count'])

          mean                               count
직무   Developer           HR     Marketer Developer   HR Marketer
부서
개발팀     5000.0          NaN          NaN       4.0  NaN      NaN
마케팅팀       NaN          NaN  4066.666667       NaN  NaN      3.0
인사팀        NaN  3733.333333          NaN       NaN  3.0      NaN

### 6) 서로 다른 방식 비교 — `groupby()+agg()` vs `pivot_table()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 방법 A: groupby() + agg()
result_a = df.groupby("부서")["급여"].agg(["mean", "count"])
print(result_a)

# 방법 B: pivot_table()
result_b = df.pivot_table(index="부서", values="급여", aggfunc=["mean", "count"])
print(result_b)
```

</details>

In [140]:
# 방법 A: groupby() + agg()
result_a = df.groupby('부서')['급여'].agg(['mean', 'count'])
print(result_a)


# 방법 B: pivot_table()
result_b = df.pivot_table(index = '부서', values = '급여', aggfunc = ['mean', 'count'])
print(result_b)

             mean  count
부서
개발팀   5000.000000      4
마케팅팀  4066.666667      3
인사팀   3733.333333      3
             mean count
               급여    급여
부서
개발팀   5000.000000     4
마케팅팀  4066.666667     3
인사팀   3733.333333     3

| 구분 | `groupby()` + `agg()` | `pivot_table()` |
|---|---|---|
| 결과 형태 | 그룹 기준이 인덱스인 표 | 엑셀 피벗테이블과 유사한 표 (행/열 기준을 각각 지정 가능) |
| 행과 열 모두 기준 지정 | 불편함 (컬럼 하나만 인덱스로) | `index`와 `columns`를 각각 지정해서 2차원 표로 정리 가능 |
| 사용 난이도 | 비교적 간단하고 직관적 | 옵션이 많아 유연하지만 살짝 더 복잡 |
| 언제 사용? | 하나의 기준으로만 그룹화할 때 | 두 개 이상의 범주를 행/열로 교차해서 보고 싶을 때 (엑셀 피벗과 비슷한 리포트) |

> 💡 **핵심 요약**: 단순히 "하나의 기준으로 그룹화해서 통계 내기"는 `groupby()`가 간편하고, "두 범주를 행/열로 교차시킨 표"가 필요하면 `pivot_table()`이 더 적합합니다. 실제로 `pivot_table()`은 내부적으로 `groupby()`를 활용해서 만들어져 있습니다.

### 7) 결과 컬럼명을 바로 지정하기 — Named Aggregation

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
result = df.groupby("부서").agg(
    평균급여=("급여", "mean"),
    최대급여=("급여", "max"),
    인원수=("이름", "count")
)
print(result)
```

</details>

In [ ]:
# 코드 입력

> 💡 `agg({"급여": "mean"})` 방식은 결과 컬럼명이 원래 컬럼명(`급여`) 그대로 나오지만, `agg(새컬럼명=("원본컬럼", "함수"))` 형태의 Named Aggregation을 쓰면 결과 컬럼명을 원하는 대로 바로 지정할 수 있어 보고서용 표를 만들 때 특히 편리합니다.

### 8) 구간으로 나눠서 그룹화 — `cut()`, `qcut()`

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df["나이대"] = pd.cut(df["나이"], bins=[0, 30, 40, 100],
                     labels=["30세 이하", "31~40세", "41세 이상"])
print(df.groupby("나이대", observed=True)["급여"].mean())

df["급여등급"] = pd.qcut(df["급여"], q=3, labels=["하", "중", "상"])
print(df["급여등급"].value_counts())
```

</details>

In [144]:
# 코드 입력

df['나이대'] = pd.cut(df['나이'], bins = [0, 30, 40, 100], 
                   labels = ['30세 이하', '31 ~ 40세', '40세 이상'])

df['급여등급'] = pd.qcut(df['급여'], q = 3, labels = ['하', '중', '상'])
df
print(df['급여등급'].value_counts())

급여등급
하    4
중    3
상    3
Name: count, dtype: int64

> 💡 `cut()`은 직접 지정한 경계값(`bins`)으로 구간을 나누고, `qcut()`은 각 구간에 데이터 개수가 고르게 들어가도록 자동으로 경계를 정합니다. 나이·급여처럼 연속된 수치를 "구간(범주)"으로 바꾼 뒤 `groupby()`와 연결하면 "나이대별 평균 급여"처럼 훨씬 해석하기 쉬운 분석이 가능해집니다.
>
> ⚠️ 결측치(`NaN`)가 있는 값을 `cut()`에 넣으면 결과도 `NaN`으로 남습니다. 본격적인 결측치 처리는 CH09에서 다룹니다.

### 9) 교차표 심화 — `crosstab()`을 비율로 보기 (`normalize`)

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(pd.crosstab(df["부서"], df["도시"]))                        # 기본: 빈도수(개수)
print(pd.crosstab(df["부서"], df["도시"], normalize="index"))     # 행(부서) 기준 비율
print(pd.crosstab(df["부서"], df["도시"], normalize="columns"))   # 열(도시) 기준 비율
```

</details>

In [ ]:
# 코드 입력

> 💡 `normalize`는 개수 대신 비율로 바꿔줍니다. `normalize="index"`는 "각 부서 안에서 도시별 비중", `normalize="columns"`는 "각 도시 안에서 부서별 비중"으로, 기준 방향이 달라지면 해석도 완전히 달라지니 어느 쪽을 100%로 보는지 항상 확인하세요.
>
> 합계 행/열을 추가하는 `margins=True` 옵션도 있는데, 이는 CH09(데이터 병합)의 `pivot_table()` 심화에서 자세히 다룹니다.

---

## ⚠️ 자주 하는 실수

> ⚠️ `groupby("부서")`만 실행하고 뒤에 집계 함수(`.mean()` 등)를 안 붙여서 결과가 이상한 객체로만 보이는 경우가 흔합니다.

> ⚠️ `agg()`에 딕셔너리를 사용할 때 컬럼명 오타로 `KeyError`가 나는 경우가 있습니다.

> ⚠️ `pivot_table()`에서 `values`에 해당하는 조합이 없는 경우 `NaN`이 나오는 것을 에러로 착각하는 경우가 있습니다 (정상 동작입니다).

> ⚠️ `qcut()`은 값이 많이 겹칠 경우 지정한 구간 개수만큼 정확히 나뉘지 않을 수 있습니다 — 이럴 땐 `duplicates="drop"` 옵션을 사용합니다.

> ⚠️ `crosstab(normalize=...)`에서 `"index"`와 `"columns"`의 기준 방향을 헷갈려 비율 해석을 반대로 하는 경우가 있습니다.

---

## 🚀 실무에서는?

> 🚀 "부서별 평균 급여", "지역별 매출 합계", "요일별 방문자 수"처럼 실무 리포트의 대부분은 그룹 분석의 결과물입니다. `groupby()`와 `pivot_table()`은 매출 대시보드, 인사 데이터 분석 등 거의 모든 비즈니스 리포트에서 사용됩니다. 또한 원본 수치를 그대로 비교하기보다 "구간(나이대, 매출 등급 등)"으로 나눠 그룹 간 차이를 비교하는 경우가 매우 많습니다. `cut()`/`qcut()`으로 연속값을 구간화하고 `groupby()`로 비교하는 패턴은 보고서·대시보드에서 가장 자주 쓰이는 조합 중 하나이며, 다음 챕터(CH08 시각화)에서 막대그래프로 바로 이어집니다.

---

## 🧩 Check Point

**Q1.** `groupby()`만 실행하고 아무 집계 함수도 붙이지 않으면? ① 에러 발생 ② 자동으로 평균 계산 ③ GroupBy 객체만 생성 (계산 안 됨) ④ 원본 그대로 반환
<details><summary>정답</summary>③ GroupBy 객체만 생성 (계산 안 됨)</details>

**Q2.** 그룹별 계산 결과를 원본과 같은 행 개수로 유지해 새 컬럼으로 붙이고 싶을 때 사용하는 것은? ① agg() ② transform() ③ filter() ④ crosstab()
<details><summary>정답</summary>② transform()</details>

**Q3.** 연속된 수치를 직접 지정한 경계값으로 구간화할 때 사용하는 함수는? ① groupby() ② cut() ③ agg() ④ pivot_table()
<details><summary>정답</summary>② cut()</details>

**Q4.** `crosstab()`에서 "각 부서 안에서의 도시별 비중"을 보려면 `normalize`에 무엇을 지정해야 하나요? ① `"index"` ② `"columns"` ③ `True` ④ `"all"`
<details><summary>정답</summary>① `"index"` — 행(부서)을 기준으로 100%가 됩니다</details>

---

## 💻 실습

> 🔧 아래 코드 블록은 ipynb 셀로 그대로 변환됩니다. 난이도가 단계적으로 올라갑니다.

In [ ]:
# TODO 1 (기본 groupby): 부서별 나이 평균을 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.groupby("부서")["나이"].mean())
```

</details>

In [186]:
# 코드 입력
df.groupby('부서')['나이'].mean()

부서
개발팀     35.5
마케팅팀    36.0
인사팀     30.0
Name: 나이, dtype: float64

In [ ]:
# TODO 2 (다중 집계): 부서별 급여의 평균, 합계, 개수를 agg()로 한 번에 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.groupby("부서")["급여"].agg(["mean", "sum", "count"]))
```

</details>

In [187]:
# 코드 입력
df.groupby('부서')['급여'].agg(['mean', 'sum', 'count'])

             mean    sum  count
부서
개발팀   5000.000000  20000      4
마케팅팀  4066.666667  12200      3
인사팀   3733.333333  11200      3

In [ ]:
# TODO 3 (다중 기준): 부서와 직무 두 가지 기준으로 그룹화해 급여 평균을 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.groupby(["부서", "직무"])["급여"].mean())
```

</details>

In [188]:
# 코드 입력
df.groupby(['부서', '직무'])['급여'].mean()

부서    직무
개발팀   Developer    5000.000000
마케팅팀  Marketer     4066.666667
인사팀   HR           3733.333333
Name: 급여, dtype: float64

In [ ]:
# TODO 4 (transform): 각 직원의 급여와 소속 부서 평균 급여를 나란히 비교하는 컬럼을 추가하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
df["부서평균급여"] = df.groupby("부서")["급여"].transform("mean")
print(df[["이름", "부서", "급여", "부서평균급여"]])
```

</details>

In [190]:
# 코드 입력
df["부서평균급여"] = df.groupby("부서")["급여"].transform("mean")
print(df[["이름", "부서", "급여", "부서평균급여"]])

    이름    부서    급여       부서평균급여
0  김민준   개발팀  4200  5000.000000
1  이서연  마케팅팀  3800  4066.666667
2  박도윤   개발팀  5600  5000.000000
3  최지우   인사팀  3600  3733.333333
4  정하윤  마케팅팀  4100  4066.666667
5  강서준   개발팀  6200  5000.000000
6  조예은   인사팀  3900  3733.333333
7  윤지호  마케팅팀  4300  4066.666667
8  임수아   개발팀  4000  5000.000000
9  한도현   인사팀  3700  3733.333333

In [ ]:
# TODO 5 (pivot_table): 부서를 행, 도시를 열로 하는 피벗테이블을 만들어 급여 평균을 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.pivot_table(index="부서", columns="도시", values="급여"))
```

</details>

In [195]:
# 코드 입력
df.pivot_table(index = '부서', columns = '도시', values = '급여', aggfunc = 'mean')

도시        대구      부산      서울      인천
부서
개발팀   4000.0     NaN  4900.0  6200.0
마케팅팀     NaN  3800.0  4200.0     NaN
인사팀   3600.0  3900.0  3700.0     NaN

In [ ]:
# TODO 6 (Named Aggregation): 부서별 급여의 평균과 최댓값을
#         "평균급여","최대급여" 컬럼명으로 한 번에 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.groupby("부서").agg(평균급여=("급여", "mean"), 최대급여=("급여", "max")))
```

</details>

In [196]:
# 코드 입력
df.groupby('부서').agg(평균급여 = ("급여", 'mean'), 최대급여 = ("급여", 'max'))

             평균급여  최대급여
부서
개발팀   5000.000000  6200
마케팅팀  4066.666667  4300
인사팀   3733.333333  3900

In [ ]:
# TODO 7 (cut): 나이를 [0,30,40,100] 구간으로 나눠 "나이대" 컬럼을 만들고,
#         나이대별 인원수를 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
df["나이대"] = pd.cut(df["나이"], bins=[0, 30, 40, 100],
                     labels=["30세 이하", "31~40세", "41세 이상"])
print(df["나이대"].value_counts())
```

</details>

In [199]:
# 코드 입력
df['나이대'] = pd.cut(df['나이'], bins = [0, 30, 40, 100], 
                   labels = ['30세 이하', '31 ~ 40세', '40세 이상'])

print(df['나이대'].value_counts())

나이대
31 ~ 40세    5
30세 이하      3
40세 이상      2
Name: count, dtype: int64

In [ ]:
# TODO 8 (crosstab 심화): 부서-도시 교차표를 행(부서) 기준 비율로 출력하세요 (normalize="index")

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(pd.crosstab(df["부서"], df["도시"], normalize="index"))
```

</details>

In [200]:
# 코드 입력
print(pd.crosstab(df["부서"], df["도시"], normalize="index"))

도시          대구        부산        서울    인천
부서
개발팀   0.250000  0.000000  0.500000  0.25
마케팅팀  0.000000  0.333333  0.666667  0.00
인사팀   0.333333  0.333333  0.333333  0.00

---

## 📝 실습 과제

In [ ]:
# 과제 1
# crosstab()으로 부서-직무 조합별 인원수를 표로 만드세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
pd.crosstab(df["부서"], df["직무"])
```

</details>

In [201]:
# 코드 입력
pd.crosstab(df['부서'], df['직무'])

직무    Developer  HR  Marketer
부서
개발팀           4   0         0
마케팅팀          0   0         3
인사팀           0   3         0

In [ ]:
# 과제 2
# filter()를 이용해 평균 급여가 4000 미만인 부서의 직원들만 골라내세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
#과제 2 답안

df.groupby("부서").filter(lambda x: x["급여"].mean() < 4000)
```

</details>

In [206]:
# 코드 입력
df.groupby('부서').filter(lambda x: x['급여'].mean() < 4000)

    이름  나이   부서  직무    급여  도시       부서평균급여       나이대 급여등급  나이순위
3  최지우  26  인사팀  HR  3600  대구  3733.333333    30세 이하    하  10.0
6  조예은  31  인사팀  HR  3900  부산  3733.333333  31 ~ 40세    하   7.0
9  한도현  33  인사팀  HR  3700  서울  3733.333333  31 ~ 40세    하   6.0

In [ ]:
# 과제 3
# agg()에 딕셔너리를 사용해 부서별로 "나이는 평균", "급여는 최댓값"을 동시에 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 3 답안

df.groupby("부서").agg({
    "나이": "mean",
    "급여": "max"
})
```

</details>

In [207]:
# 코드 입력
df.groupby('부서').agg({
    "나이" : "mean",
    "급여" : "max"
})

        나이    급여
부서
개발팀   35.5  6200
마케팅팀  36.0  4300
인사팀   30.0  3900

In [ ]:
# 과제 4
# qcut()으로 급여를 3구간("하","중","상")으로 나누고, 등급별 평균 나이를 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df["급여등급"] = pd.qcut(df["급여"], q=3, labels=["하", "중", "상"])

df.groupby("급여등급")["나이"].mean()
```

</details>

In [210]:
# 코드 입력
df['급여등급'] = pd.qcut(df['급여'], q = 3, labels = ['하', '중', '상'])

df.groupby('급여등급')['나이'].mean()

C:\Users\k6221\AppData\Local\Temp\ipykernel_48152\11303044.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('급여등급')['나이'].mean()

급여등급
하    31.000000
중    31.333333
상    40.666667
Name: 나이, dtype: float64

In [211]:
# 과제 5
# crosstab()에 normalize="columns" 옵션을 사용해 도시별 부서 비율을 확인하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 5 답안

pd.crosstab(df["부서"], df["도시"], normalize="columns")
```

</details>

In [212]:
# 코드 입력
pd.crosstab(df['도시'], df['부서'], normalize = "columns")

부서   개발팀      마케팅팀       인사팀
도시
대구  0.25  0.000000  0.333333
부산  0.00  0.333333  0.333333
서울  0.50  0.666667  0.333333
인천  0.25  0.000000  0.000000

---

## 📌 핵심 정리

- `groupby(기준)`으로 그룹을 나눈 뒤 `.mean()`, `.sum()` 등 집계 함수를 붙여야 계산됨
- `agg(["함수1","함수2"])` 또는 `agg({"컬럼":"함수"})`로 여러 통계를 한 번에
- `agg(새컬럼명=("원본컬럼","함수"))` Named Aggregation으로 결과 컬럼명을 바로 지정
- `transform()`: 그룹 계산 결과를 원본 행 개수 그대로 유지 (새 컬럼 추가에 유용)
- `filter()`: 조건을 만족하는 그룹 전체를 선택
- `cut()`/`qcut()`: 연속값을 구간(범주)으로 변환 → `groupby()`와 연결해 구간별 비교
- `crosstab()`: 빈도표, `normalize="index"/"columns"`로 비율 확인 / `pivot_table()`: 통계 계산이 가능한 유연한 교차표

---

---
## 🎉 정규 수업 완료!

EDA 기초, 데이터 선택, 그룹 분석 3개 소단원을 모두 다뤘습니다 (정렬·순위·`idxmax()`, `at`/`iat`, `set_index()`/`query()`, Named Aggregation, `cut()`/`qcut()` 등 심화 내용 포함). 자율학습(추가 심화: MultiIndex, `apply()` 커스텀 함수 활용)은 `CH07-04`, `CH07-05` md 문서를 참고해주세요.